---
# tasks file for debian_patching

- name: Ensure that need-restarting binary is present
  ansible.builtin.dnf:
    name: "{{ debian_patching_required_packages }}"
    state: present

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    exclude: "{{ debian_patching_exclude_packages | default(omit) }}"
  when: debian_patching_method == "all"

- name: Apply security patches only
  ansible.builtin.dnf:
    name: "*"
    security: true
    state: latest
    exclude: "{{ debian_patching_exclude_packages | default(omit) }}"
  when: debian_patching_method == "security"

- name: Apply bugfix patches only
  ansible.builtin.dnf:
    name: "*"
    bugfix: true
    state: latest
    exclude: "{{ debian_patching_exclude_packages | default(omit) }}"
  when: debian_patching_method == "bugfix"

- name: Verify if restart is required
  ansible.builtin.command:
    cmd: needs-restarting --reboothint
  register: __debian_patching_need_restart
  failed_when: __debian_patching_need_restart.rc > 1

- name: Inform user if reboot is required
  ansible.builtin.debug:
    msg: "Reboot is required to apply patches."
  when: __debian_patching_need_restart.rc == 1

- name: Reboot host
  ansible.builtin.reboot:
    reboot_timeout: "{{ debian_patching_reboot_timeout }}"
  when: debian_patching_auto_reboot | bool and __debian_patching_need_restart.rc == 1