galaxy_info:
  author: certipath
  description: Auto Reboot Linux Server
  company: CertiPath.io

  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: Debian
      versions:
        - all